## 1차 전처리

In [42]:
import pandas as pd
import ast

file_path = '영화리뷰_왓챠피디아.csv'
reviews_df = pd.read_csv(file_path)

reviews_df = reviews_df.dropna(subset=['reviews'])

reviews_df['reviews'] = reviews_df['reviews'].apply(ast.literal_eval)

expanded_reviews_df = reviews_df.explode('reviews').reset_index(drop=True)

print(expanded_reviews_df.head())

   title  rating                                            reviews
0  서울의 봄     3.9                                하아 대머리 죽었지만 다시 죽이고픔
1  서울의 봄     3.9       야만과 무능의 그 겨울밤에 대한 분노가 시종 팽팽한 긴장감 속에서 펄펄 끓는다.
2  서울의 봄     3.9                                   예정된 비극을 바라보는 참담함
3  서울의 봄     3.9  "실패하면 반역, 성공하면 혁명 아닙니까?"\n\n그럼에도, 다시금 봄이 찾아왔기 ...
4  서울의 봄     3.9  거울 속 비친 전두광 자신의 모습이 어떠했을까 아주 잠깐일지 몰라도 분명 전두광의 ...

In [43]:
expanded_reviews_df['reviews'] = expanded_reviews_df['reviews'].apply(lambda x: x.replace('\n\n', ''))
expanded_reviews_df['reviews'] = expanded_reviews_df['reviews'].apply(lambda x: x.replace('\n', ''))

In [44]:
expanded_reviews_df

      title  rating                                            reviews
0     서울의 봄     3.9                                하아 대머리 죽었지만 다시 죽이고픔
1     서울의 봄     3.9       야만과 무능의 그 겨울밤에 대한 분노가 시종 팽팽한 긴장감 속에서 펄펄 끓는다.
2     서울의 봄     3.9                                   예정된 비극을 바라보는 참담함
3     서울의 봄     3.9  "실패하면 반역, 성공하면 혁명 아닙니까?"그럼에도, 다시금 봄이 찾아왔기 때문에그...
4     서울의 봄     3.9  거울 속 비친 전두광 자신의 모습이 어떠했을까 아주 잠깐일지 몰라도 분명 전두광의 ...
...     ...     ...                                                ...
1231    엘비스     3.5  정신없는 초반부보다는 엘비스의 고독한 내면이 느껴지는 후반부로 갈수록 깊이 빠져든다...
1232    엘비스     3.5                                 가슴 벅찬 포인트보기 벅찬 분량들
1233    엘비스     3.5  "노래가 없으면 변화도 없다." - Elvis Aaron Presley "엘비스 이...
1234    엘비스     3.5                                  별을 향한 탐닉, 증오, 중독.
1235    엘비스     3.5            진정 음악을 사랑한, 일찍 세상을 떠났지만 한 시대를 풍미했던 레전드.

[1236 rows x 3 columns]

In [45]:
expanded_reviews_df.to_csv('영화리뷰_왓챠피디아_확장.csv', index=False, escapechar='\\')

In [46]:
df_cine = pd.read_csv("영화리뷰_씨네21_크롤링.csv")
df_cine

,Unnamed: 0,movie_title,running_time,release_date,viewer,director,actors,production,screenplay_writers,director_of_photography,editors,original_author,distributor,importer,review_count,review_id,review_date,review_rating,review_comment
0,0,스트레인지 월드,101분,2022-11-23,"112,910명","돈 홀, 퀴 응우옌,","['제이크 질렌할', '루시 리우', '데니스 퀘이드', '자부키 영-화이트', '...",NaN,['퀴 응우옌'],[],[],[],['월트디즈니컴퍼니코리아㈜'],['월트디즈니컴퍼니코리아㈜'],0,NaN,NaN,NaN,NaN
1,1,싱글 인 서울,NaN,2023-11-29,"400,681명","박범수,","['이동욱', '임수정', '이솜', '장현성', '김지영']",NaN,[],[],[],[],[],[],3,filmone1,2023-12-28 23:40:47,6.0,박범수 감독이 연출한 <싱글 인 서울>은 책을 출판하기 위해 함께하는 두 남녀의 사...
2,2,싱글 인 서울,NaN,2023-11-29,"400,681명","박범수,","['이동욱', '임수정', '이솜', '장현성', '김지영']",NaN,[],[],[],[],[],[],3,thrill5,2023-12-27 19:54:55,10.0,한국에서 청년층이 연애하지 않는 이유를 사회적인 제약으로만 생각하려는 \n\n경향이...
3,3,싱글 인 서울,NaN,2023-11-29,"400,681명","박범수,","['이동욱', '임수정', '이솜', '장현성', '김지영']",NaN,[],[],[],[],[],[],3,hwachul92,2023-11-30 21:15:44,8.0,평범하면서 가을 느낌을 솔솔 풍기며 힐링을 주는 로맨틱코미디영화였습니다! 싱글을 전...
4,4,아바타: 물의 길,192분,2022-12-14,"10,805,065명","제임스 카메론,","['조 샐다나', '샘 워싱턴', '시고니 위버']",NaN,[],[],[],[],['월트디즈니컴퍼니코리아㈜'],['월트디즈니컴퍼니코리아㈜'],4,filmone1,2023-01-05 08:32:50,8.0,제임스 카메론 감독이 연출한 <아바타: 물의 길>은 13년 만에 제작된 <아바타>의...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
674,674,더 문,129분,2023-08-02,"486,060명","김용화,","['설경구', '도경수', '김희애', '박병은', '조한철', '최병모', '홍승희']",CJ ENM STUDIOS,[],[],[],[],['CJ ENM'],[],3,hwachul92,2023-08-02 21:54:28,8.0,달과 우주를 배경으로 긴장과 몰입 그리고 감동을 함께 선사한 SF영화였습니다! 한국...
675,675,더 문,129분,2023-08-02,"486,060명","김용화,","['설경구', '도경수', '김희애', '박병은', '조한철', '최병모', '홍승희']",CJ ENM STUDIOS,[],[],[],[],['CJ ENM'],[],3,263185326081682,2023-05-09 16:54:45,10.0,Actor Doh Kyungsoo's big screen comeback!
676,676,타겟,101분,2023-08-30,"424,916명","박희곤,","['신혜선', '김성균', '임철수', '이주영', '강태오', '임성재', '금새록']",조병연,"['박희곤', '김동후']",[],[],[],['플러스엠 엔터테인먼트'],[],3,21457255,2024-02-04 20:19:55,6.0,억울한 일을 당하는 역할은 서영희 이후 신혜선이 갑
677,677,타겟,101분,2023-08-30,"424,916명","박희곤,","['신혜선', '김성균', '임철수', '이주영', '강태오', '임성재', '금새록']",조병연,"['박희곤', '김동후']",[],[],[],['플러스엠 엔터테인먼트'],[],3,filmone1,2023-09-19 00:37:52,5.0,박희곤 감독이 연출한 <타겟>은 중고거래 사기를 당한 여성이 복수를 하려다 벌어지는...
678,678,타겟,101분,2023-08-30,"424,916명","박희곤,","['신혜선', '김성균', '임철수', '이주영', '강태오', '임성재', '금새록']",조병연,"['박희곤', '김동후']",[],[],[],['플러스엠 엔터테인먼트'],[],3,hwachul92,2023-08-31 20:39:26,8.0,소름돋으면서 긴장감을 형성시킨 서스펜스범죄영화였습니다! 중고거래를 명목으로 사기 및...

In [47]:
df_cine = df_cine.loc[:,['movie_title','review_rating','review_comment']]

In [48]:
df_cine.columns = ['title', 'rating', 'reviews']

In [49]:
df_cine

         title  rating                                            reviews
0     스트레인지 월드     NaN                                                NaN
1      싱글 인 서울     6.0  박범수 감독이 연출한 <싱글 인 서울>은 책을 출판하기 위해 함께하는 두 남녀의 사...
2      싱글 인 서울    10.0  한국에서 청년층이 연애하지 않는 이유를 사회적인 제약으로만 생각하려는 \n\n경향이...
3      싱글 인 서울     8.0  평범하면서 가을 느낌을 솔솔 풍기며 힐링을 주는 로맨틱코미디영화였습니다! 싱글을 전...
4    아바타: 물의 길     8.0  제임스 카메론 감독이 연출한 <아바타: 물의 길>은 13년 만에 제작된 <아바타>의...
..         ...     ...                                                ...
674        더 문     8.0  달과 우주를 배경으로 긴장과 몰입 그리고 감동을 함께 선사한 SF영화였습니다! 한국...
675        더 문    10.0          Actor Doh Kyungsoo's big screen comeback!
676         타겟     6.0                       억울한 일을 당하는 역할은 서영희 이후 신혜선이 갑
677         타겟     5.0  박희곤 감독이 연출한 <타겟>은 중고거래 사기를 당한 여성이 복수를 하려다 벌어지는...
678         타겟     8.0  소름돋으면서 긴장감을 형성시킨 서스펜스범죄영화였습니다! 중고거래를 명목으로 사기 및...

[679 rows x 3 columns]

In [50]:
expanded_reviews_df[expanded_reviews_df['title'] == ' 틀맨']['title'] = '젠틀맨'

C:\Users\kkksk\AppData\Local\Temp\ipykernel_9220\4038663456.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  expanded_reviews_df[expanded_reviews_df['title'] == ' 틀맨']['title'] = '젠틀맨'

In [51]:
df_cine['reviews'] = df_cine['reviews'].astype(str)

In [52]:
df_cine['reviews'] = df_cine['reviews'].apply(lambda x: x.replace('\n\n', ''))
df_cine['reviews'] = df_cine['reviews'].apply(lambda x: x.replace('\n', ''))

In [53]:
df_cine.dropna(inplace = True)

In [54]:
df_cine.to_csv("영화리뷰_씨네21.csv", index = False)